version: "2"
services:
  backend:
    build: ./api-backend
    restart: on-failure
    ports:
      - "8001:8001"
  frontend:
    build: ./api-frontend
    environment:
      API_BACKEND_URL: backend
      API_BACKEND_PORT: 8001
    restart: on-failure
    links:
      - backend
    ports:
      - "8000:8000"

